trigger:
  batch: true
  branches:
    include:
    - feature/*

pr:
- feature/*

stages:
- stage: Build
  dependsOn: []
  jobs:
  - job: Build
    steps:
    - template: azure-pipelines/build.yml

- stage: Test
  displayName: Test
  dependsOn: []
  jobs:
  - job: Test
    strategy:
      matrix:
        linux:
          vmImage: ubuntu-latest
    pool:
      vmImage: $(vmImage)
    steps:
    - template: azure-pipelines/test.yml

# TODO: add compliance stage