name: Merge omnisharp master into feature/lsp_tools_host
on: [push]
#  schedule:
#    - cron:  '0 */3 * * *'
jobs:
  Merge-Omnisharp-Master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: omnisharp/omnisharp-vscode
      - name: Get changes from Omnisharp-vscode/master
        run: |
          git remote add upstream https://github.com/OmniSharp/omnisharp-vscode.git
          git fetch upstream master:upstream-master
          git reset --hard upstream-master
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: merge-omnisharp-master
  Merge-LSP-Engine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: omnisharp/omnisharp-vscode
      - name: Get changes from Omnisharp-vscode/feature/lsp-engine
        run: |
          git remote add upstream https://github.com/OmniSharp/omnisharp-vscode.git
          git fetch upstream feature/lsp-engine:upstream-feature/lsp-engine
          git reset --hard upstream-feature/lsp-engine
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: merge-omnisharp-lsp-engine