steps:

# The server package is downloaded from NuGet
- task: NuGetAuthenticate@1

- task: NodeTool@0
  displayName: 'Install Node.js 16.x'
  inputs:
    versionSpec: '16.x'

- script: |
    npm ci
    npm i -g gulp
  displayName: 'Install dependencies'

- script: npm run compile
  displayName: 'Compile'

- script: npm run vscode:prepublish
  displayName: 'Prepublish VSIXs'
